import BgGame from "./BgImages/BgOfTheGame.png"
import Gamelogo from "./TextImages/RONDA.png"
import StartGame from "./TextImages/Start Game.png"
import GameRules from "./TextImages/Game Rules.png"
import OfflineGame from "./TextImages/Offline Game.png"
import OnlineGame from "./TextImages/Online Game.png"
import FullSc from "./BgImages/FullScreenButton.png"
import ExitFullSc from "./BgImages/ExitFullScreenButton.png"
import RedFullSc from "./BgImages/RedFullScreenButton.png"
import RedExitFullSc from "./BgImages/RedExitFullScreenButton.png"
import GoBackPageButton from "./BgImages/GoBackPageButton.png"
import twoPlayers from "./TextImages/2Players.png"
import treePlayers from "./TextImages/3Players.png"
import fourPlayers from "./TextImages/4Players.png"
import ChosePlayersNB from "./TextImages/Choose Game Size.png"
import cartat from "./Cards Images/Cartat.png"
import Sife from "./Cards Images/ChargeSife.png"
import BgPlayGround from "./BgImages/PlayGroundBackground.png"
import SettingsButtonImg from "./BgImages/SettingsButtonImg.png"
import CadrePlayerName from "./BgImages/CadrePlayerName.png"
import CatProfile from "./ProfilesPictures/cat.png"
import CardBack from "./Cards Images/CardsBack.png"
import wahdtb9 from "./Cards Images/1 tb9.jpg"
import jojtb9 from "./Cards Images/2 tb9.jpg"
import tlatatb9 from "./Cards Images/3 tb9.jpg"
import rab3atb9 from "./Cards Images/4 tb9.jpg"
import khamsatb9 from "./Cards Images/5 tb9.jpg"
import setatb9 from "./Cards Images/6 tb9.jpg"
import sab3atb9 from "./Cards Images/7 tb9.jpg"
import axratb9 from "./Cards Images/10 tb9.jpg"
import hdaxtb9 from "./Cards Images/11 tb9.jpg"
import tnachtb9 from "./Cards Images/12 tb9.jpg"
import wahdgu3 from "./Cards Images/1 gur3.jpg"
import jojgu3 from "./Cards Images/2 gur3.jpg"
import tlatagu3 from "./Cards Images/3 gur3.jpg"
import rab3agu3 from "./Cards Images/4 gur3.jpg"
import khamsagu3 from "./Cards Images/5 gur3.jpg"
import setagu3 from "./Cards Images/6 gur3.jpg"
import sab3agu3 from "./Cards Images/7 gur3.jpg"
import axragu3 from "./Cards Images/10 gur3.jpg"
import hdaxgu3 from "./Cards Images/11 gur3.jpg"
import tnachgu3 from "./Cards Images/12 gur3.jpg"
import wahdDhb from "./Cards Images/1 dhb.jpg"
import jojDhb from "./Cards Images/2 dhb.jpg"
import tlataDhb from "./Cards Images/3 dhb.jpg"
import rab3aDhb from "./Cards Images/4 dhb.jpg"
import khamsaDhb from "./Cards Images/5 dhb.jpg"
import setaDhb from "./Cards Images/6 dhb.jpg"
import sab3aDhb from "./Cards Images/7 dhb.jpg"
import axraDhb from "./Cards Images/10 dhb.jpg"
import hdaxDhb from "./Cards Images/11 dhb.jpg"
import tnachDhb from "./Cards Images/12 dhb.jpg"
import wahdsife from "./Cards Images/1 sife.jpg"
import jojsife from "./Cards Images/2 sife.jpg"
import tlatasife from "./Cards Images/3 sife.jpg"
import rab3asife from "./Cards Images/4 sife.jpg"
import khamsasife from "./Cards Images/5 sife.jpg"
import setasife from "./Cards Images/6 sife.jpg"
import sab3asife from "./Cards Images/7 sife.jpg"
import axrasife from "./Cards Images/10 sife.jpg"
import hdaxsife from "./Cards Images/11 sife.jpg"
import tnachsife from "./Cards Images/12 sife.jpg"

export {BgGame, StartGame, GameRules, Gamelogo, OfflineGame, OnlineGame,
        GoBackPageButton, ExitFullSc, FullSc, RedExitFullSc, RedFullSc, twoPlayers, treePlayers, 
        fourPlayers, ChosePlayersNB, cartat, Sife, BgPlayGround, SettingsButtonImg,
        CadrePlayerName, CatProfile, CardBack, 
        wahdtb9, jojtb9, tlatatb9, rab3atb9, khamsatb9, setatb9, sab3atb9, axratb9, hdaxtb9, tnachtb9,    
        wahdDhb, jojDhb, tlataDhb, rab3aDhb, khamsaDhb, setaDhb, sab3aDhb, axraDhb, hdaxDhb, tnachDhb,    
        wahdgu3, jojgu3, tlatagu3, rab3agu3, khamsagu3, setagu3, sab3agu3, axragu3, hdaxgu3, tnachgu3,    
        wahdsife, jojsife, tlatasife, rab3asife, khamsasife, setasife, sab3asife, axrasife, hdaxsife, tnachsife}; 